title = "Vishal Kancharla"
base_url = "https://vish-kancharla.github.io"
description = "A Zola-theme based on Bear Blog."

compile_sass = false
build_search_index = false

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
date_format="%d %b, %Y"
webserver_sends_csp_headers=true

[[extra.main_menu]]
name = "Projects"
url = "@/projects.md"

[[extra.main_menu]]
name = "TIL"
url = "@/til.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"